pipeline{
    agent any
        stages{
                stage("Clone Repository"){
                /*cloning the Repository to work space*/
        steps{
            checkout scm
            }
        }

        stage('Build Image'){
        steps{
            sh 'sudo docker build -t myfib:v1 .'
            
        }
    }
    stage('Run Image'){
        steps{
            sh 'sudo docker run -d --name fib myfib:v1'
        }
    }
    stage('Testing'){
        steps{
            echo 'Testing'
        }
    }
    }
}